### PR TITLE
add 2018-06-25-up-annual-report

### PR DESCRIPTION
**Pull request by apetro**
Add a further iterated version of the uPortal annual report.

Will create a version, URL that focuses on uPortal, yielding a referenceable, marketable version of this report for promoting uPortal.

Clarifies calls to action.

### CODE REVIEW

**Comment by apetro** [comment]
cf. [uportal-user@ thread](https://groups.google.com/a/apereo.org/d/msg/uportal-user/6bSRQjvpY8I/G_ccXIWKDgAJ).

**Comment by apetro** [comment]
Invoking lazy consensus. Absent feedback otherwise, will look to update the date on this post to current and merge sometime after 2018-06-12.

**Comment by jimhelwig** [comment]
I am slightly unclear as to what this is. @apetro, is this your personal blog post on the annual report? Or are you viewing this as the what we could call the sanctioned uPortal annual report? Knowing this will help me better comment.

**Comment by jimhelwig** [comment]
I would like to see something like this with the  imprimatur of the uPSC. It would seem a little more "official" or definitive. I'm fine with noting Andrew as the primary author. I am not exactly sure at the moment how to propose that change, but it would be replacing "wearing individual contributor [hat][ASF hats]." with "on behalf of the uPortal Steering Committee."

**Comment by apetro** [comment]
Discussed f2f with @jimhelwig . I think we're going a direction of this here is a blog post in an individual voice. Maybe even a good blog post. And yes there ought to be an annual report in uPortal Steering's voice. And that report maybe even ought to take some points from or even evolve from this text. But that uPortal-steering-voice statement, if any, isn't this.

I find myself reminded of [Apache's inspirational language on hats](https://www.apache.org/foundation/how-it-works.html#hats).

> All of those ASF people implicitly have multiple hats, especially the Board, the other officers, and the PMC chairs. They sometimes need to talk about a matter of policy, so to avoid appearing to be expressing a personal opinion, they will state that they are talking in their special capacity. However, most of the time this is not necessary, personal opinions work well.

And reminded of [the disclaimer on `apereo.github.io`](https://github.com/apereo/apereo.github.io/issues/39), and especially [its prior articulation](https://github.com/apereo/apereo.github.io/pull/40),

> This blog is BY NO MEANS an official voice of the Apereo Foundation. All official statements on behalf of the Apereo Foundation are made by the Chair, ED, or other authorized individuals. All opinions, views, notes, anecdotes, stories and comments expressed via this blog solely, purely and exclusively belong to individual authors and do not express or reflect the official policy, position, views or opinions of the Apereo Foundation itself.

Most of the time personal opinions work well, and apereo.github.io (and this post) are not an official statement of the Foundation. For the official Apereo version, read [the PDF annual report](https://www.apereo.org/sites/default/files/content/pdfs/Annual%20Report%203June18.pdf). For a personal take, read this `apereo.github.io` post.

I do appreciate the review; feedback on even posts in a personal voice make for better posts.

While apereo.github.io isn't an official voice of the Apereo Foundation (maybe see [the Apereo website itself's blog](https://www.apereo.org/blog) for that?), this apereo.github.io is *something* and maybe that something should gain some structure over time, cf. https://github.com/apereo/apereo.github.io/issues/22 .

**Pull request merged**
